name: build-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel semver
          pip install -r requirements.txt

      - name: Get latest version from PyPI and increment
        id: version
        run: |
          package_name="space-exploration-common-lib"
          response=$(curl -s https://pypi.org/pypi/$package_name/json)
          latest_version=$(echo $response | jq -r '.info.version')
          if [ "$latest_version" == "null" ]; then
            new_version="0.0.1"
          else
            new_version=$(python -c "import semver; print(semver.bump_patch('$latest_version'))")
          fi
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Set version environment variable
        run: echo "VERSION=${{ env.new_version }}" > .env

      - name: Build package
        run: |
          source .env
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: success()
        run: |
          python -m pip install --upgrade twine
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Push new tag
        run: |
          if [ -n "${{ env.new_version }}" ]; then
            git tag ${{ env.new_version }}
            git push origin ${{ env.new_version }}
          else
            echo "No new version tag to push."
          fi
